import { SupportedLanguageCode } from "../types";

// All interface chrome (not AI-generated content) is pre-translated here rather
// than machine-translated at runtime — this keeps the app usable even fully
// offline and avoids inconsistent phrasing on every load. Grow this file for
// any new UI string; never hardcode English strings in components.
export type StringKey =
  | "tapToSpeak"
  | "listening"
  | "tapToStop"
  | "analyzing"
  | "verdictTrue"
  | "verdictFalse"
  | "verdictMisleading"
  | "verdictUnclear"
  | "noInternetTitle"
  | "smsButtonLabel"
  | "smsSent"
  | "smsFailed"
  | "yourQuestion"
  | "listenAgain"
  | "askAnother"
  | "history"
  | "settings"
  | "selectLanguage"
  | "recordingError"
  | "networkError"
  | "genericError"
  | "welcomeTitle"
  | "welcomeSubtitle"
  | "queuedOffline"
  | "micPermissionDenied"
  | "clearHistory"
  | "noHistoryYet"
  | "autoDetect"
  | "forwardWhatsApp"
  | "getStarted"
  | "enterPhoneNumber"
  | "phoneNumberHint"
  | "sendCode"
  | "otpSentTitle"
  | "verifyCode"
  | "resendCode"
  | "otpIncorrect"
  | "otpConfigMissing"
  | "otpTestModeHint"
  | "locationPermissionTitle"
  | "locationPermissionBody"
  | "allowLocation"
  | "skipForNow"
  | "continueLabel"
  | "typeQuestionPlaceholder"
  | "send"
  | "orTypeInstead"
  | "profile"
  | "contactUs"
  | "faqs"
  | "resetOnboarding"
  | "resetOnboardingConfirmTitle"
  | "resetOnboardingConfirmBody"
  | "cancel"
  | "phoneNumberLabel"
  | "notSetYet"
  | "yourLocation"
  | "locationNotSet"
  | "appVersion"
  | "contactUsIntro"
  | "contactPhone"
  | "contactEmail"
  | "faqQ1"
  | "faqA1"
  | "faqQ2"
  | "faqA2"
  | "faqQ3"
  | "faqA3"
  | "faqQ4"
  | "faqA4"
  | "smsTrialUnverified"
  | "addPhoneNumberFirst"
  | "welcomeBack"
  | "quickActions"
  | "askByVoice"
  | "askByTyping"
  | "moreOptions"
  | "yourDistrict"
  | "latestSchemes"
  | "schemesLoadFailed"
  | "schemesEmpty";

type StringTable = Record<StringKey, string>;

const en: StringTable = {
  tapToSpeak: "Tap to Speak",
  listening: "Listening…",
  tapToStop: "Tap to Stop",
  analyzing: "Checking your question…",
  verdictTrue: "TRUE",
  verdictFalse: "FALSE",
  verdictMisleading: "MISLEADING",
  verdictUnclear: "UNCLEAR",
  noInternetTitle: "No internet?",
  smsButtonLabel: "Get result by SMS",
  smsSent: "Sent! You'll get a text with the answer soon.",
  smsFailed: "Could not send SMS. Please check the phone number.",
  yourQuestion: "Your question",
  listenAgain: "Listen again",
  askAnother: "Ask another question",
  history: "Past questions",
  settings: "Settings",
  selectLanguage: "Choose your language",
  recordingError: "Could not record audio. Please try again.",
  networkError: "No internet connection.",
  genericError: "Something went wrong. Please try again.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "Ask about news, schemes, or farming advice",
  queuedOffline: "Saved. We'll check this when you're back online.",
  micPermissionDenied: "Please allow microphone access to use Sat-Yukt.",
  clearHistory: "Clear history",
  noHistoryYet: "No past questions yet",
  autoDetect: "Auto-detect",
  forwardWhatsApp: "Forward a WhatsApp message",
  getStarted: "Get Started",
  enterPhoneNumber: "Enter your phone number",
  phoneNumberHint: "We'll send you a code to verify it's you",
  sendCode: "Send Code",
  otpSentTitle: "Enter the code we sent you",
  verifyCode: "Verify",
  resendCode: "Resend code",
  otpIncorrect: "That code is incorrect. Please try again.",
  otpConfigMissing: "OTP verification is not set up yet. Please try again later.",
  otpTestModeHint: "Test mode: enter 000000 to continue.",
  locationPermissionTitle: "Share your location?",
  locationPermissionBody: "This helps us show news and schemes relevant to your area.",
  allowLocation: "Allow Location",
  skipForNow: "Skip for now",
  continueLabel: "Continue",
  typeQuestionPlaceholder: "Type your question…",
  send: "Send",
  orTypeInstead: "Or type your question",
  profile: "Profile",
  contactUs: "Contact Us",
  faqs: "Frequently Asked Questions",
  resetOnboarding: "Reset onboarding (for testing)",
  resetOnboardingConfirmTitle: "Reset onboarding?",
  resetOnboardingConfirmBody: "This will take you back through language, phone, and location setup next time you open the app.",
  cancel: "Cancel",
  phoneNumberLabel: "Phone number",
  notSetYet: "Not set yet",
  yourLocation: "Your location",
  locationNotSet: "Location not shared",
  appVersion: "App version",
  contactUsIntro: "Have a question, problem, or feedback? Reach us here:",
  contactPhone: "Call us",
  contactEmail: "Email us",
  faqQ1: "Is Sat-Yukt free to use?",
  faqA1: "Yes, Sat-Yukt is completely free. You only need a phone to ask your question.",
  faqQ2: "Do I need internet to use it?",
  faqA2: "No. If you have no internet, tap \"Get result by SMS\" and we will text you the answer.",
  faqQ3: "Which languages are supported?",
  faqA3: "Sat-Yukt works in Hindi, English, Marathi, Tamil, Telugu, Bengali, Gujarati, Punjabi, and Kannada.",
  faqQ4: "Is my phone number kept private?",
  faqA4: "Yes. Your phone number is only used to send you SMS results and is never shared with anyone else.",
  smsTrialUnverified: "This app's SMS service is still in test mode and can only text a few approved numbers. Please ask the app owner to add your number.",
  addPhoneNumberFirst: "Please add your phone number in Settings first.",
  welcomeBack: "Welcome back",
  quickActions: "Quick Actions",
  askByVoice: "Ask by Voice",
  askByTyping: "Ask by Typing",
  moreOptions: "More",
  yourDistrict: "Your area",
  latestSchemes: "Latest Government Schemes",
  schemesLoadFailed: "Could not load schemes right now. Please try again later.",
  schemesEmpty: "No schemes to show right now.",
};

const hi: StringTable = {
  tapToSpeak: "बोलने के लिए दबाएँ",
  listening: "सुन रहे हैं…",
  tapToStop: "रोकने के लिए दबाएँ",
  analyzing: "आपके सवाल की जाँच हो रही है…",
  verdictTrue: "सही",
  verdictFalse: "गलत",
  verdictMisleading: "भ्रामक",
  verdictUnclear: "स्पष्ट नहीं",
  noInternetTitle: "इंटरनेट नहीं है?",
  smsButtonLabel: "SMS से जवाब पाएँ",
  smsSent: "भेज दिया गया! जल्द ही जवाब SMS में मिलेगा।",
  smsFailed: "SMS नहीं भेजा जा सका। कृपया फ़ोन नंबर जाँचें।",
  yourQuestion: "आपका सवाल",
  listenAgain: "फिर से सुनें",
  askAnother: "एक और सवाल पूछें",
  history: "पुराने सवाल",
  settings: "सेटिंग्स",
  selectLanguage: "अपनी भाषा चुनें",
  recordingError: "आवाज़ रिकॉर्ड नहीं हो सकी। कृपया फिर से कोशिश करें।",
  networkError: "इंटरनेट कनेक्शन नहीं है।",
  genericError: "कुछ गलत हो गया। कृपया फिर से कोशिश करें।",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "खबर, योजना, या खेती की सलाह के बारे में पूछें",
  queuedOffline: "सेव हो गया। इंटरनेट आने पर हम जाँच करेंगे।",
  micPermissionDenied: "Sat-Yukt इस्तेमाल करने के लिए माइक्रोफ़ोन की अनुमति दें।",
  clearHistory: "इतिहास मिटाएँ",
  noHistoryYet: "अभी तक कोई सवाल नहीं",
  autoDetect: "अपने आप पहचानें",
  forwardWhatsApp: "व्हाट्सएप संदेश भेजें",
  getStarted: "शुरू करें",
  enterPhoneNumber: "अपना फ़ोन नंबर डालें",
  phoneNumberHint: "आपकी पहचान की पुष्टि के लिए हम एक कोड भेजेंगे",
  sendCode: "कोड भेजें",
  otpSentTitle: "हमने जो कोड भेजा है वह डालें",
  verifyCode: "पुष्टि करें",
  resendCode: "कोड दोबारा भेजें",
  otpIncorrect: "यह कोड गलत है। कृपया फिर से कोशिश करें।",
  otpConfigMissing: "OTP सत्यापन अभी तैयार नहीं है। कृपया बाद में फिर कोशिश करें।",
  otpTestModeHint: "टेस्ट मोड: आगे बढ़ने के लिए 000000 डालें।",
  locationPermissionTitle: "अपनी जगह साझा करें?",
  locationPermissionBody: "इससे हम आपके क्षेत्र से जुड़ी खबरें और योजनाएँ दिखा पाएँगे।",
  allowLocation: "जगह की अनुमति दें",
  skipForNow: "अभी छोड़ें",
  continueLabel: "आगे बढ़ें",
  typeQuestionPlaceholder: "अपना सवाल लिखें…",
  send: "भेजें",
  orTypeInstead: "या अपना सवाल लिखें",
  profile: "प्रोफ़ाइल",
  contactUs: "संपर्क करें",
  faqs: "अक्सर पूछे जाने वाले सवाल",
  resetOnboarding: "ऑनबोर्डिंग रीसेट करें (टेस्टिंग के लिए)",
  resetOnboardingConfirmTitle: "ऑनबोर्डिंग रीसेट करें?",
  resetOnboardingConfirmBody: "अगली बार ऐप खोलने पर आपको भाषा, फ़ोन और लोकेशन सेटअप फिर से करना होगा।",
  cancel: "रद्द करें",
  phoneNumberLabel: "फ़ोन नंबर",
  notSetYet: "अभी सेट नहीं है",
  yourLocation: "आपकी जगह",
  locationNotSet: "जगह साझा नहीं की गई",
  appVersion: "ऐप वर्शन",
  contactUsIntro: "कोई सवाल, समस्या या सुझाव है? यहाँ संपर्क करें:",
  contactPhone: "हमें कॉल करें",
  contactEmail: "हमें ईमेल करें",
  faqQ1: "क्या Sat-Yukt इस्तेमाल करना मुफ़्त है?",
  faqA1: "हाँ, Sat-Yukt पूरी तरह मुफ़्त है। आपको बस अपना सवाल पूछने के लिए एक फ़ोन चाहिए।",
  faqQ2: "क्या इसे इस्तेमाल करने के लिए इंटरनेट चाहिए?",
  faqA2: "नहीं। अगर इंटरनेट नहीं है, तो \"SMS से जवाब पाएँ\" दबाएँ और हम आपको जवाब भेज देंगे।",
  faqQ3: "कौन सी भाषाएँ उपलब्ध हैं?",
  faqA3: "Sat-Yukt हिंदी, अंग्रेज़ी, मराठी, तमिल, तेलुगु, बंगाली, गुजराती, पंजाबी और कन्नड़ में काम करता है।",
  faqQ4: "क्या मेरा फ़ोन नंबर सुरक्षित रहता है?",
  faqA4: "हाँ। आपका फ़ोन नंबर सिर्फ़ आपको SMS जवाब भेजने के लिए इस्तेमाल होता है और किसी और के साथ साझा नहीं किया जाता।",
  smsTrialUnverified: "इस ऐप की SMS सेवा अभी टेस्ट मोड में है और केवल कुछ स्वीकृत नंबरों पर संदेश भेज सकती है। कृपया ऐप के मालिक से अपना नंबर जोड़ने के लिए कहें।",
  addPhoneNumberFirst: "कृपया पहले Settings में अपना फ़ोन नंबर जोड़ें।",
  welcomeBack: "वापसी पर स्वागत है",
  quickActions: "त्वरित कार्य",
  askByVoice: "बोलकर पूछें",
  askByTyping: "लिखकर पूछें",
  moreOptions: "और विकल्प",
  yourDistrict: "आपका क्षेत्र",
  latestSchemes: "नवीनतम सरकारी योजनाएँ",
  schemesLoadFailed: "अभी योजनाएँ लोड नहीं हो सकीं। कृपया बाद में फिर कोशिश करें।",
  schemesEmpty: "अभी दिखाने के लिए कोई योजना नहीं है।",
};

const mr: StringTable = {
  tapToSpeak: "बोलण्यासाठी दाबा",
  listening: "ऐकत आहे…",
  tapToStop: "थांबवण्यासाठी दाबा",
  analyzing: "तुमचा प्रश्न तपासत आहे…",
  verdictTrue: "खरे",
  verdictFalse: "खोटे",
  verdictMisleading: "दिशाभूल करणारे",
  verdictUnclear: "अस्पष्ट",
  noInternetTitle: "इंटरनेट नाही?",
  smsButtonLabel: "SMS ने उत्तर मिळवा",
  smsSent: "पाठवले! लवकरच उत्तर SMS मध्ये मिळेल.",
  smsFailed: "SMS पाठवता आले नाही. फोन नंबर तपासा.",
  yourQuestion: "तुमचा प्रश्न",
  listenAgain: "पुन्हा ऐका",
  askAnother: "आणखी एक प्रश्न विचारा",
  history: "जुने प्रश्न",
  settings: "सेटिंग्ज",
  selectLanguage: "तुमची भाषा निवडा",
  recordingError: "आवाज रेकॉर्ड होऊ शकला नाही. पुन्हा प्रयत्न करा.",
  networkError: "इंटरनेट कनेक्शन नाही.",
  genericError: "काहीतरी चूक झाली. पुन्हा प्रयत्न करा.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "बातम्या, योजना किंवा शेती सल्ल्याबद्दल विचारा",
  queuedOffline: "जतन केले. इंटरनेट आल्यावर आम्ही तपासू.",
  micPermissionDenied: "Sat-Yukt वापरण्यासाठी मायक्रोफोनची परवानगी द्या.",
  clearHistory: "इतिहास साफ करा",
  noHistoryYet: "अजून कोणतेही प्रश्न नाहीत",
  autoDetect: "आपोआप ओळखा",
  forwardWhatsApp: "व्हॉट्सअ‍ॅप संदेश फॉरवर्ड करा",
  getStarted: "सुरू करा",
  enterPhoneNumber: "तुमचा फोन नंबर टाका",
  phoneNumberHint: "तुमची ओळख पडताळण्यासाठी आम्ही एक कोड पाठवू",
  sendCode: "कोड पाठवा",
  otpSentTitle: "आम्ही पाठवलेला कोड टाका",
  verifyCode: "पडताळणी करा",
  resendCode: "कोड पुन्हा पाठवा",
  otpIncorrect: "हा कोड चुकीचा आहे. कृपया पुन्हा प्रयत्न करा.",
  otpConfigMissing: "OTP पडताळणी अजून तयार नाही. कृपया नंतर पुन्हा प्रयत्न करा.",
  otpTestModeHint: "चाचणी मोड: पुढे जाण्यासाठी 000000 टाका.",
  locationPermissionTitle: "तुमचे ठिकाण शेअर करायचे?",
  locationPermissionBody: "यामुळे आम्ही तुमच्या भागाशी संबंधित बातम्या आणि योजना दाखवू शकू.",
  allowLocation: "ठिकाणाला परवानगी द्या",
  skipForNow: "आत्ता वगळा",
  continueLabel: "पुढे जा",
  typeQuestionPlaceholder: "तुमचा प्रश्न लिहा…",
  send: "पाठवा",
  orTypeInstead: "किंवा तुमचा प्रश्न लिहा",
  profile: "प्रोफाइल",
  contactUs: "आमच्याशी संपर्क साधा",
  faqs: "वारंवार विचारले जाणारे प्रश्न",
  resetOnboarding: "ऑनबोर्डिंग रीसेट करा (चाचणीसाठी)",
  resetOnboardingConfirmTitle: "ऑनबोर्डिंग रीसेट करायचे?",
  resetOnboardingConfirmBody: "पुढच्या वेळी अ‍ॅप उघडल्यावर तुम्हाला भाषा, फोन आणि लोकेशन सेटअप पुन्हा करावे लागेल.",
  cancel: "रद्द करा",
  phoneNumberLabel: "फोन नंबर",
  notSetYet: "अजून सेट केलेले नाही",
  yourLocation: "तुमचे ठिकाण",
  locationNotSet: "ठिकाण शेअर केलेले नाही",
  appVersion: "अ‍ॅप व्हर्जन",
  contactUsIntro: "काही प्रश्न, समस्या किंवा सूचना आहे? इथे संपर्क करा:",
  contactPhone: "आम्हाला कॉल करा",
  contactEmail: "आम्हाला ईमेल करा",
  faqQ1: "Sat-Yukt वापरणे मोफत आहे का?",
  faqA1: "होय, Sat-Yukt पूर्णपणे मोफत आहे. तुमचा प्रश्न विचारण्यासाठी फक्त फोन हवा.",
  faqQ2: "वापरण्यासाठी इंटरनेट लागते का?",
  faqA2: "नाही. इंटरनेट नसेल तर \"SMS ने उत्तर मिळवा\" दाबा आणि आम्ही तुम्हाला उत्तर पाठवू.",
  faqQ3: "कोणत्या भाषा उपलब्ध आहेत?",
  faqA3: "Sat-Yukt हिंदी, इंग्रजी, मराठी, तमिळ, तेलुगु, बंगाली, गुजराती, पंजाबी आणि कन्नडमध्ये काम करते.",
  faqQ4: "माझा फोन नंबर सुरक्षित राहतो का?",
  faqA4: "होय. तुमचा फोन नंबर फक्त SMS उत्तर पाठवण्यासाठी वापरला जातो आणि इतर कोणाशीही शेअर केला जात नाही.",
  smsTrialUnverified: "या अ‍ॅपची SMS सेवा अजून चाचणी मोडमध्ये आहे आणि फक्त काही मंजूर नंबरांना संदेश पाठवू शकते. कृपया अ‍ॅपच्या मालकाला तुमचा नंबर जोडण्यास सांगा.",
  addPhoneNumberFirst: "कृपया आधी Settings मध्ये तुमचा फोन नंबर जोडा.",
  welcomeBack: "परत स्वागत आहे",
  quickActions: "त्वरित कृती",
  askByVoice: "बोलून विचारा",
  askByTyping: "लिहून विचारा",
  moreOptions: "आणखी पर्याय",
  yourDistrict: "तुमचा भाग",
  latestSchemes: "नवीनतम सरकारी योजना",
  schemesLoadFailed: "सध्या योजना लोड होऊ शकल्या नाहीत. कृपया नंतर पुन्हा प्रयत्न करा.",
  schemesEmpty: "सध्या दाखवण्यासाठी कोणतीही योजना नाही.",
};

// Tamil, Telugu, Bengali, Gujarati, Punjabi, Kannada follow the same pattern.
// Included fully so the app is genuinely usable, not just scaffolded, in all
// nine languages advertised in the language picker.
const ta: StringTable = {
  tapToSpeak: "பேச தட்டவும்",
  listening: "கேட்கிறது…",
  tapToStop: "நிறுத்த தட்டவும்",
  analyzing: "உங்கள் கேள்வியை சரிபார்க்கிறது…",
  verdictTrue: "உண்மை",
  verdictFalse: "பொய்",
  verdictMisleading: "தவறாக வழிநடத்தும்",
  verdictUnclear: "தெளிவில்லை",
  noInternetTitle: "இணையம் இல்லையா?",
  smsButtonLabel: "SMS மூலம் பதில் பெறவும்",
  smsSent: "அனுப்பப்பட்டது! விரைவில் பதில் SMS-ல் வரும்.",
  smsFailed: "SMS அனுப்ப முடியவில்லை. தொலைபேசி எண்ணை சரிபார்க்கவும்.",
  yourQuestion: "உங்கள் கேள்வி",
  listenAgain: "மீண்டும் கேளுங்கள்",
  askAnother: "மற்றொரு கேள்வி கேளுங்கள்",
  history: "பழைய கேள்விகள்",
  settings: "அமைப்புகள்",
  selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
  recordingError: "ஒலியை பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
  networkError: "இணைய இணைப்பு இல்லை.",
  genericError: "ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "செய்தி, திட்டங்கள் அல்லது விவசாய ஆலோசனை பற்றி கேளுங்கள்",
  queuedOffline: "சேமிக்கப்பட்டது. இணையம் வந்தவுடன் சரிபார்ப்போம்.",
  micPermissionDenied: "Sat-Yukt-ஐப் பயன்படுத்த மைக்ரோஃபோன் அனுமதி தேவை.",
  clearHistory: "வரலாற்றை அழிக்கவும்",
  noHistoryYet: "இதுவரை கேள்விகள் இல்லை",
  autoDetect: "தானாக கண்டறியவும்",
  forwardWhatsApp: "வாட்ஸ்அப் செய்தியை அனுப்பவும்",
  getStarted: "தொடங்குங்கள்",
  enterPhoneNumber: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
  phoneNumberHint: "உங்களை உறுதிப்படுத்த ஒரு குறியீட்டை அனுப்புவோம்",
  sendCode: "குறியீட்டை அனுப்பு",
  otpSentTitle: "நாங்கள் அனுப்பிய குறியீட்டை உள்ளிடவும்",
  verifyCode: "சரிபார்க்கவும்",
  resendCode: "குறியீட்டை மீண்டும் அனுப்பு",
  otpIncorrect: "இந்த குறியீடு தவறானது. மீண்டும் முயற்சிக்கவும்.",
  otpConfigMissing: "OTP சரிபார்ப்பு இன்னும் தயாராகவில்லை. பின்னர் முயற்சிக்கவும்.",
  otpTestModeHint: "சோதனை முறை: தொடர 000000 எனத் தட்டச்சு செய்யவும்.",
  locationPermissionTitle: "உங்கள் இருப்பிடத்தைப் பகிரவா?",
  locationPermissionBody: "இது உங்கள் பகுதிக்கு ஏற்ற செய்திகள் மற்றும் திட்டங்களைக் காட்ட உதவும்.",
  allowLocation: "இருப்பிடத்தை அனுமதிக்கவும்",
  skipForNow: "இப்போது தவிர்க்கவும்",
  continueLabel: "தொடரவும்",
  typeQuestionPlaceholder: "உங்கள் கேள்வியை தட்டச்சு செய்யவும்…",
  send: "அனுப்பு",
  orTypeInstead: "அல்லது உங்கள் கேள்வியை தட்டச்சு செய்யவும்",
  profile: "சுயவிவரம்",
  contactUs: "எங்களை தொடர்பு கொள்ளுங்கள்",
  faqs: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
  resetOnboarding: "ஆன்போர்டிங்கை மீட்டமைக்கவும் (சோதனைக்காக)",
  resetOnboardingConfirmTitle: "ஆன்போர்டிங்கை மீட்டமைக்கவா?",
  resetOnboardingConfirmBody: "அடுத்த முறை ஆப்ஸைத் திறக்கும்போது மொழி, தொலைபேசி மற்றும் இருப்பிடத்தை மீண்டும் அமைக்க வேண்டும்.",
  cancel: "ரத்து செய்",
  phoneNumberLabel: "தொலைபேசி எண்",
  notSetYet: "இன்னும் அமைக்கப்படவில்லை",
  yourLocation: "உங்கள் இருப்பிடம்",
  locationNotSet: "இருப்பிடம் பகிரப்படவில்லை",
  appVersion: "ஆப்ஸ் பதிப்பு",
  contactUsIntro: "கேள்வி, பிரச்சனை அல்லது கருத்து உள்ளதா? இங்கே தொடர்பு கொள்ளுங்கள்:",
  contactPhone: "எங்களை அழைக்கவும்",
  contactEmail: "எங்களுக்கு மின்னஞ்சல் அனுப்பவும்",
  faqQ1: "Sat-Yukt பயன்படுத்த இலவசமா?",
  faqA1: "ஆம், Sat-Yukt முழுவதும் இலவசம். உங்கள் கேள்வியைக் கேட்க ஒரு தொலைபேசி மட்டுமே தேவை.",
  faqQ2: "இதைப் பயன்படுத்த இணையம் தேவையா?",
  faqA2: "இல்லை. இணையம் இல்லையெனில் \"SMS மூலம் பதில் பெறவும்\" என்பதைத் தட்டவும், நாங்கள் பதிலை அனுப்புவோம்.",
  faqQ3: "எந்த மொழிகள் ஆதரிக்கப்படுகின்றன?",
  faqA3: "Sat-Yukt இந்தி, ஆங்கிலம், மராத்தி, தமிழ், தெலுங்கு, வங்காளம், குஜராத்தி, பஞ்சாபி மற்றும் கன்னடத்தில் செயல்படுகிறது.",
  faqQ4: "என் தொலைபேசி எண் தனிப்பட்டதாக வைக்கப்படுமா?",
  faqA4: "ஆம். உங்கள் தொலைபேசி எண் SMS பதில்களை அனுப்ப மட்டுமே பயன்படுத்தப்படும், வேறு யாருடனும் பகிரப்படாது.",
  smsTrialUnverified: "இந்த ஆப்ஸின் SMS சேவை இன்னும் சோதனை பயன்முறையில் உள்ளது, சில அங்கீகரிக்கப்பட்ட எண்களுக்கு மட்டுமே அனுப்ப முடியும். உங்கள் எண்ணைச் சேர்க்க ஆப்ஸ் உரிமையாளரிடம் கேளுங்கள்.",
  addPhoneNumberFirst: "முதலில் Settings-இல் உங்கள் தொலைபேசி எண்ணைச் சேர்க்கவும்.",
  welcomeBack: "மீண்டும் வரவேற்கிறோம்",
  quickActions: "விரைவு செயல்கள்",
  askByVoice: "பேசி கேளுங்கள்",
  askByTyping: "தட்டச்சு செய்து கேளுங்கள்",
  moreOptions: "மேலும்",
  yourDistrict: "உங்கள் பகுதி",
  latestSchemes: "சமீபத்திய அரசு திட்டங்கள்",
  schemesLoadFailed: "இப்போது திட்டங்களை ஏற்ற முடியவில்லை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
  schemesEmpty: "இப்போது காட்ட திட்டங்கள் இல்லை.",
};

const te: StringTable = {
  tapToSpeak: "మాట్లాడటానికి నొక్కండి",
  listening: "వింటోంది…",
  tapToStop: "ఆపడానికి నొక్కండి",
  analyzing: "మీ ప్రశ్నను తనిఖీ చేస్తోంది…",
  verdictTrue: "నిజం",
  verdictFalse: "అబద్ధం",
  verdictMisleading: "తప్పుదారి పట్టించే",
  verdictUnclear: "అస్పష్టం",
  noInternetTitle: "ఇంటర్నెట్ లేదా?",
  smsButtonLabel: "SMS ద్వారా సమాధానం పొందండి",
  smsSent: "పంపబడింది! త్వరలో సమాధానం SMSలో వస్తుంది.",
  smsFailed: "SMS పంపలేకపోయాము. ఫోన్ నంబర్ తనిఖీ చేయండి.",
  yourQuestion: "మీ ప్రశ్న",
  listenAgain: "మళ్ళీ వినండి",
  askAnother: "మరో ప్రశ్న అడగండి",
  history: "పాత ప్రశ్నలు",
  settings: "సెట్టింగ్‌లు",
  selectLanguage: "మీ భాషను ఎంచుకోండి",
  recordingError: "ఆడియో రికార్డ్ కాలేదు. మళ్ళీ ప్రయత్నించండి.",
  networkError: "ఇంటర్నెట్ కనెక్షన్ లేదు.",
  genericError: "ఏదో తప్పు జరిగింది. మళ్ళీ ప్రయత్నించండి.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "వార్తలు, పథకాలు లేదా వ్యవసాయ సలహా గురించి అడగండి",
  queuedOffline: "సేవ్ చేయబడింది. ఇంటర్నెట్ వచ్చాక తనిఖీ చేస్తాము.",
  micPermissionDenied: "Sat-Yukt ఉపయోగించడానికి మైక్రోఫోన్ అనుమతి ఇవ్వండి.",
  clearHistory: "చరిత్రను తుడిచివేయండి",
  noHistoryYet: "ఇంకా ప్రశ్నలు లేవు",
  autoDetect: "స్వయంచాలకంగా గుర్తించు",
  forwardWhatsApp: "వాట్సాప్ సందేశాన్ని ఫార్వర్డ్ చేయండి",
  getStarted: "ప్రారంభించండి",
  enterPhoneNumber: "మీ ఫోన్ నంబర్ నమోదు చేయండి",
  phoneNumberHint: "మిమ్మల్ని నిర్ధారించడానికి మేము ఒక కోడ్ పంపుతాము",
  sendCode: "కోడ్ పంపండి",
  otpSentTitle: "మేము పంపిన కోడ్‌ని నమోదు చేయండి",
  verifyCode: "ధృవీకరించండి",
  resendCode: "కోడ్‌ని మళ్ళీ పంపండి",
  otpIncorrect: "ఈ కోడ్ తప్పు. దయచేసి మళ్ళీ ప్రయత్నించండి.",
  otpConfigMissing: "OTP ధృవీకరణ ఇంకా సిద్ధంగా లేదు. దయచేసి తర్వాత ప్రయత్నించండి.",
  otpTestModeHint: "టెస్ట్ మోడ్: కొనసాగించడానికి 000000 నమోదు చేయండి.",
  locationPermissionTitle: "మీ లొకేషన్‌ను షేర్ చేయాలా?",
  locationPermissionBody: "ఇది మీ ప్రాంతానికి సంబంధించిన వార్తలు మరియు పథకాలను చూపడానికి సహాయపడుతుంది.",
  allowLocation: "లొకేషన్‌ను అనుమతించండి",
  skipForNow: "ప్రస్తుతానికి వదిలేయండి",
  continueLabel: "కొనసాగించండి",
  typeQuestionPlaceholder: "మీ ప్రశ్నను టైప్ చేయండి…",
  send: "పంపండి",
  orTypeInstead: "లేదా మీ ప్రశ్నను టైప్ చేయండి",
  profile: "ప్రొఫైల్",
  contactUs: "మమ్మల్ని సంప్రదించండి",
  faqs: "తరచుగా అడిగే ప్రశ్నలు",
  resetOnboarding: "ఆన్‌బోర్డింగ్‌ను రీసెట్ చేయండి (టెస్టింగ్ కోసం)",
  resetOnboardingConfirmTitle: "ఆన్‌బోర్డింగ్‌ను రీసెట్ చేయాలా?",
  resetOnboardingConfirmBody: "తర్వాతిసారి యాప్ తెరిచినప్పుడు మీరు భాష, ఫోన్ మరియు లొకేషన్ సెటప్ మళ్ళీ చేయాల్సి ఉంటుంది.",
  cancel: "రద్దు చేయండి",
  phoneNumberLabel: "ఫోన్ నంబర్",
  notSetYet: "ఇంకా సెట్ చేయలేదు",
  yourLocation: "మీ లొకేషన్",
  locationNotSet: "లొకేషన్ షేర్ చేయలేదు",
  appVersion: "యాప్ వెర్షన్",
  contactUsIntro: "ఏదైనా ప్రశ్న, సమస్య లేదా అభిప్రాయం ఉందా? ఇక్కడ సంప్రదించండి:",
  contactPhone: "మాకు కాల్ చేయండి",
  contactEmail: "మాకు ఇమెయిల్ చేయండి",
  faqQ1: "Sat-Yukt ఉపయోగించడం ఉచితమా?",
  faqA1: "అవును, Sat-Yukt పూర్తిగా ఉచితం. మీ ప్రశ్న అడగడానికి మీకు ఒక ఫోన్ మాత్రమే కావాలి.",
  faqQ2: "దీన్ని ఉపయోగించడానికి ఇంటర్నెట్ అవసరమా?",
  faqA2: "లేదు. ఇంటర్నెట్ లేకపోతే \"SMS ద్వారా సమాధానం పొందండి\" నొక్కండి, మేము మీకు సమాధానం పంపుతాము.",
  faqQ3: "ఏ భాషలు మద్దతు ఇవ్వబడతాయి?",
  faqA3: "Sat-Yukt హిందీ, ఇంగ్లీష్, మరాఠీ, తమిళం, తెలుగు, బెంగాలీ, గుజరాతీ, పంజాబీ మరియు కన్నడలో పనిచేస్తుంది.",
  faqQ4: "నా ఫోన్ నంబర్ ప్రైవేట్‌గా ఉంచబడుతుందా?",
  faqA4: "అవును. మీ ఫోన్ నంబర్ మీకు SMS సమాధానాలు పంపడానికి మాత్రమే ఉపయోగించబడుతుంది మరియు ఇతరులతో ఎప్పుడూ పంచుకోబడదు.",
  smsTrialUnverified: "ఈ యాప్ యొక్క SMS సేవ ఇంకా టెస్ట్ మోడ్‌లో ఉంది మరియు కొన్ని ఆమోదించబడిన నంబర్లకు మాత్రమే పంపగలదు. దయచేసి మీ నంబర్‌ను జోడించమని యాప్ యజమానిని అడగండి.",
  addPhoneNumberFirst: "దయచేసి ముందుగా Settings లో మీ ఫోన్ నంబర్‌ను జోడించండి.",
  welcomeBack: "తిరిగి స్వాగతం",
  quickActions: "త్వరిత చర్యలు",
  askByVoice: "మాట్లాడి అడగండి",
  askByTyping: "టైప్ చేసి అడగండి",
  moreOptions: "మరిన్ని",
  yourDistrict: "మీ ప్రాంతం",
  latestSchemes: "తాజా ప్రభుత్వ పథకాలు",
  schemesLoadFailed: "ఇప్పుడు పథకాలను లోడ్ చేయలేకపోయాము. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.",
  schemesEmpty: "ఇప్పుడు చూపించడానికి పథకాలు లేవు.",
};

const bn: StringTable = {
  tapToSpeak: "কথা বলতে চাপুন",
  listening: "শুনছে…",
  tapToStop: "থামাতে চাপুন",
  analyzing: "আপনার প্রশ্ন যাচাই হচ্ছে…",
  verdictTrue: "সত্য",
  verdictFalse: "মিথ্যা",
  verdictMisleading: "বিভ্রান্তিকর",
  verdictUnclear: "অস্পষ্ট",
  noInternetTitle: "ইন্টারনেট নেই?",
  smsButtonLabel: "SMS-এ উত্তর পান",
  smsSent: "পাঠানো হয়েছে! শীঘ্রই SMS-এ উত্তর পাবেন।",
  smsFailed: "SMS পাঠানো যায়নি। ফোন নম্বর যাচাই করুন।",
  yourQuestion: "আপনার প্রশ্ন",
  listenAgain: "আবার শুনুন",
  askAnother: "আরেকটি প্রশ্ন করুন",
  history: "পুরনো প্রশ্ন",
  settings: "সেটিংস",
  selectLanguage: "আপনার ভাষা নির্বাচন করুন",
  recordingError: "অডিও রেকর্ড করা যায়নি। আবার চেষ্টা করুন।",
  networkError: "ইন্টারনেট সংযোগ নেই।",
  genericError: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "খবর, প্রকল্প, বা কৃষি পরামর্শ সম্পর্কে জিজ্ঞাসা করুন",
  queuedOffline: "সংরক্ষিত হয়েছে। ইন্টারনেট এলে যাচাই করা হবে।",
  micPermissionDenied: "Sat-Yukt ব্যবহার করতে মাইক্রোফোন অনুমতি দিন।",
  clearHistory: "ইতিহাস মুছুন",
  noHistoryYet: "এখনো কোনো প্রশ্ন নেই",
  autoDetect: "স্বয়ংক্রিয়ভাবে সনাক্ত করুন",
  forwardWhatsApp: "হোয়াটসঅ্যাপ বার্তা ফরওয়ার্ড করুন",
  getStarted: "শুরু করুন",
  enterPhoneNumber: "আপনার ফোন নম্বর দিন",
  phoneNumberHint: "আপনাকে যাচাই করতে আমরা একটি কোড পাঠাব",
  sendCode: "কোড পাঠান",
  otpSentTitle: "আমরা যে কোড পাঠিয়েছি তা দিন",
  verifyCode: "যাচাই করুন",
  resendCode: "কোড আবার পাঠান",
  otpIncorrect: "এই কোডটি ভুল। আবার চেষ্টা করুন।",
  otpConfigMissing: "OTP যাচাইকরণ এখনো প্রস্তুত নয়। পরে আবার চেষ্টা করুন।",
  otpTestModeHint: "টেস্ট মোড: চালিয়ে যেতে 000000 লিখুন।",
  locationPermissionTitle: "আপনার অবস্থান শেয়ার করবেন?",
  locationPermissionBody: "এটি আপনার এলাকার সাথে সম্পর্কিত খবর ও প্রকল্প দেখাতে সাহায্য করবে।",
  allowLocation: "অবস্থানের অনুমতি দিন",
  skipForNow: "এখন বাদ দিন",
  continueLabel: "এগিয়ে যান",
  typeQuestionPlaceholder: "আপনার প্রশ্ন লিখুন…",
  send: "পাঠান",
  orTypeInstead: "অথবা আপনার প্রশ্ন লিখুন",
  profile: "প্রোফাইল",
  contactUs: "যোগাযোগ করুন",
  faqs: "প্রায়শই জিজ্ঞাসিত প্রশ্ন",
  resetOnboarding: "অনবোর্ডিং রিসেট করুন (পরীক্ষার জন্য)",
  resetOnboardingConfirmTitle: "অনবোর্ডিং রিসেট করবেন?",
  resetOnboardingConfirmBody: "পরের বার অ্যাপ খুললে আপনাকে ভাষা, ফোন এবং অবস্থান আবার সেট করতে হবে।",
  cancel: "বাতিল করুন",
  phoneNumberLabel: "ফোন নম্বর",
  notSetYet: "এখনো সেট করা হয়নি",
  yourLocation: "আপনার অবস্থান",
  locationNotSet: "অবস্থান শেয়ার করা হয়নি",
  appVersion: "অ্যাপ সংস্করণ",
  contactUsIntro: "কোনো প্রশ্ন, সমস্যা বা মতামত আছে? এখানে যোগাযোগ করুন:",
  contactPhone: "আমাদের কল করুন",
  contactEmail: "আমাদের ইমেইল করুন",
  faqQ1: "Sat-Yukt ব্যবহার করা কি বিনামূল্যে?",
  faqA1: "হ্যাঁ, Sat-Yukt সম্পূর্ণ বিনামূল্যে। আপনার প্রশ্ন জিজ্ঞাসা করতে শুধু একটি ফোন দরকার।",
  faqQ2: "এটি ব্যবহার করতে কি ইন্টারনেট দরকার?",
  faqA2: "না। ইন্টারনেট না থাকলে \"SMS-এ উত্তর পান\" চাপুন, আমরা আপনাকে উত্তর পাঠাব।",
  faqQ3: "কোন কোন ভাষা সমর্থিত?",
  faqA3: "Sat-Yukt হিন্দি, ইংরেজি, মারাঠি, তামিল, তেলুগু, বাংলা, গুজরাটি, পাঞ্জাবি এবং কন্নড়ে কাজ করে।",
  faqQ4: "আমার ফোন নম্বর কি ব্যক্তিগত রাখা হয়?",
  faqA4: "হ্যাঁ। আপনার ফোন নম্বর শুধু SMS উত্তর পাঠাতে ব্যবহৃত হয় এবং অন্য কারো সাথে শেয়ার করা হয় না।",
  smsTrialUnverified: "এই অ্যাপের SMS পরিষেবা এখনো টেস্ট মোডে আছে এবং শুধু কিছু অনুমোদিত নম্বরে পাঠাতে পারে। আপনার নম্বর যোগ করতে অ্যাপের মালিককে বলুন।",
  addPhoneNumberFirst: "অনুগ্রহ করে প্রথমে Settings-এ আপনার ফোন নম্বর যোগ করুন।",
  welcomeBack: "আবার স্বাগতম",
  quickActions: "দ্রুত কাজ",
  askByVoice: "বলে জিজ্ঞাসা করুন",
  askByTyping: "লিখে জিজ্ঞাসা করুন",
  moreOptions: "আরও",
  yourDistrict: "আপনার এলাকা",
  latestSchemes: "সর্বশেষ সরকারি প্রকল্প",
  schemesLoadFailed: "এখন প্রকল্প লোড করা যায়নি। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
  schemesEmpty: "এখন দেখানোর মতো কোনো প্রকল্প নেই।",
};

const gu: StringTable = {
  tapToSpeak: "બોલવા માટે દબાવો",
  listening: "સાંભળી રહ્યા છીએ…",
  tapToStop: "રોકવા માટે દબાવો",
  analyzing: "તમારો પ્રશ્ન તપાસાઈ રહ્યો છે…",
  verdictTrue: "સાચું",
  verdictFalse: "ખોટું",
  verdictMisleading: "ભ્રામક",
  verdictUnclear: "અસ્પષ્ટ",
  noInternetTitle: "ઇન્ટરનેટ નથી?",
  smsButtonLabel: "SMS દ્વારા જવાબ મેળવો",
  smsSent: "મોકલાયું! ટૂંક સમયમાં SMSમાં જવાબ મળશે.",
  smsFailed: "SMS મોકલી શકાયો નથી. ફોન નંબર તપાસો.",
  yourQuestion: "તમારો પ્રશ્ન",
  listenAgain: "ફરી સાંભળો",
  askAnother: "બીજો પ્રશ્ન પૂછો",
  history: "જૂના પ્રશ્નો",
  settings: "સેટિંગ્સ",
  selectLanguage: "તમારી ભાષા પસંદ કરો",
  recordingError: "ઓડિયો રેકોર્ડ થઈ શક્યો નથી. ફરી પ્રયાસ કરો.",
  networkError: "ઇન્ટરનેટ કનેક્શન નથી.",
  genericError: "કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "સમાચાર, યોજનાઓ અથવા ખેતી સલાહ વિશે પૂછો",
  queuedOffline: "સાચવ્યું. ઇન્ટરનેટ આવ્યા પછી તપાસીશું.",
  micPermissionDenied: "Sat-Yukt વાપરવા માટે માઇક્રોફોન પરવાનગી આપો.",
  clearHistory: "ઇતિહાસ સાફ કરો",
  noHistoryYet: "હજુ સુધી કોઈ પ્રશ્નો નથી",
  autoDetect: "આપમેળે ઓળખો",
  forwardWhatsApp: "વોટ્સએપ સંદેશ ફોરવર્ડ કરો",
  getStarted: "શરૂ કરો",
  enterPhoneNumber: "તમારો ફોન નંબર દાખલ કરો",
  phoneNumberHint: "તમારી ઓળખ ચકાસવા અમે એક કોડ મોકલીશું",
  sendCode: "કોડ મોકલો",
  otpSentTitle: "અમે મોકલેલો કોડ દાખલ કરો",
  verifyCode: "ચકાસો",
  resendCode: "કોડ ફરી મોકલો",
  otpIncorrect: "આ કોડ ખોટો છે. ફરી પ્રયાસ કરો.",
  otpConfigMissing: "OTP ચકાસણી હજુ તૈયાર નથી. પછી ફરી પ્રયાસ કરો.",
  otpTestModeHint: "ટેસ્ટ મોડ: આગળ વધવા માટે 000000 દાખલ કરો.",
  locationPermissionTitle: "તમારું સ્થાન શેર કરવું છે?",
  locationPermissionBody: "આનાથી અમે તમારા વિસ્તારને લગતા સમાચાર અને યોજનાઓ બતાવી શકીશું.",
  allowLocation: "સ્થાનની પરવાનગી આપો",
  skipForNow: "હમણાં છોડો",
  continueLabel: "આગળ વધો",
  typeQuestionPlaceholder: "તમારો પ્રશ્ન લખો…",
  send: "મોકલો",
  orTypeInstead: "અથવા તમારો પ્રશ્ન લખો",
  profile: "પ્રોફાઇલ",
  contactUs: "અમારો સંપર્ક કરો",
  faqs: "વારંવાર પૂછાતા પ્રશ્નો",
  resetOnboarding: "ઓનબોર્ડિંગ રીસેટ કરો (પરીક્ષણ માટે)",
  resetOnboardingConfirmTitle: "ઓનબોર્ડિંગ રીસેટ કરવું છે?",
  resetOnboardingConfirmBody: "આગલી વખતે એપ ખોલો ત્યારે તમારે ભાષા, ફોન અને સ્થાન ફરીથી સેટ કરવું પડશે.",
  cancel: "રદ કરો",
  phoneNumberLabel: "ફોન નંબર",
  notSetYet: "હજુ સેટ નથી",
  yourLocation: "તમારું સ્થાન",
  locationNotSet: "સ્થાન શેર કરેલ નથી",
  appVersion: "એપ વર્ઝન",
  contactUsIntro: "કોઈ પ્રશ્ન, સમસ્યા કે સૂચન છે? અહીં સંપર્ક કરો:",
  contactPhone: "અમને કૉલ કરો",
  contactEmail: "અમને ઈમેલ કરો",
  faqQ1: "શું Sat-Yukt વાપરવું મફત છે?",
  faqA1: "હા, Sat-Yukt સંપૂર્ણપણે મફત છે. તમારો પ્રશ્ન પૂછવા માટે ફક્ત ફોન જોઈએ.",
  faqQ2: "શું તેનો ઉપયોગ કરવા ઈન્ટરનેટ જોઈએ?",
  faqA2: "ના. ઈન્ટરનેટ ન હોય તો \"SMS દ્વારા જવાબ મેળવો\" દબાવો, અમે તમને જવાબ મોકલીશું.",
  faqQ3: "કઈ ભાષાઓ ઉપલબ્ધ છે?",
  faqA3: "Sat-Yukt હિન્દી, અંગ્રેજી, મરાઠી, તમિલ, તેલુગુ, બંગાળી, ગુજરાતી, પંજાબી અને કન્નડમાં કામ કરે છે.",
  faqQ4: "શું મારો ફોન નંબર ખાનગી રહે છે?",
  faqA4: "હા. તમારો ફોન નંબર ફક્ત SMS જવાબ મોકલવા માટે વપરાય છે અને બીજા કોઈની સાથે શેર થતો નથી.",
  smsTrialUnverified: "આ એપની SMS સેવા હજુ ટેસ્ટ મોડમાં છે અને ફક્ત અમુક મંજૂર નંબરો પર જ મોકલી શકે છે. કૃપા કરી એપના માલિકને તમારો નંબર ઉમેરવા કહો.",
  addPhoneNumberFirst: "કૃપા કરી પહેલા Settings માં તમારો ફોન નંબર ઉમેરો.",
  welcomeBack: "ફરી સ્વાગત છે",
  quickActions: "ઝડપી ક્રિયાઓ",
  askByVoice: "બોલીને પૂછો",
  askByTyping: "લખીને પૂછો",
  moreOptions: "વધુ",
  yourDistrict: "તમારો વિસ્તાર",
  latestSchemes: "તાજેતરની સરકારી યોજનાઓ",
  schemesLoadFailed: "અત્યારે યોજનાઓ લોડ થઈ શકી નથી. કૃપા કરી પછી ફરી પ્રયાસ કરો.",
  schemesEmpty: "અત્યારે બતાવવા માટે કોઈ યોજના નથી.",
};

const pa: StringTable = {
  tapToSpeak: "ਬੋਲਣ ਲਈ ਦਬਾਓ",
  listening: "ਸੁਣ ਰਹੇ ਹਾਂ…",
  tapToStop: "ਰੋਕਣ ਲਈ ਦਬਾਓ",
  analyzing: "ਤੁਹਾਡੇ ਸਵਾਲ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ…",
  verdictTrue: "ਸਹੀ",
  verdictFalse: "ਗਲਤ",
  verdictMisleading: "ਭਰਮਾਉਣ ਵਾਲਾ",
  verdictUnclear: "ਸਪਸ਼ਟ ਨਹੀਂ",
  noInternetTitle: "ਇੰਟਰਨੈੱਟ ਨਹੀਂ ਹੈ?",
  smsButtonLabel: "SMS ਰਾਹੀਂ ਜਵਾਬ ਪਾਓ",
  smsSent: "ਭੇਜ ਦਿੱਤਾ ਗਿਆ! ਜਲਦੀ ਹੀ SMS ਵਿੱਚ ਜਵਾਬ ਮਿਲੇਗਾ।",
  smsFailed: "SMS ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ। ਫ਼ੋਨ ਨੰਬਰ ਜਾਂਚੋ।",
  yourQuestion: "ਤੁਹਾਡਾ ਸਵਾਲ",
  listenAgain: "ਦੁਬਾਰਾ ਸੁਣੋ",
  askAnother: "ਇੱਕ ਹੋਰ ਸਵਾਲ ਪੁੱਛੋ",
  history: "ਪੁਰਾਣੇ ਸਵਾਲ",
  settings: "ਸੈਟਿੰਗਾਂ",
  selectLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
  recordingError: "ਆਵਾਜ਼ ਰਿਕਾਰਡ ਨਹੀਂ ਹੋ ਸਕੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  networkError: "ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ ਹੈ।",
  genericError: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "ਖਬਰਾਂ, ਯੋਜਨਾਵਾਂ ਜਾਂ ਖੇਤੀ ਸਲਾਹ ਬਾਰੇ ਪੁੱਛੋ",
  queuedOffline: "ਸੇਵ ਹੋ ਗਿਆ। ਇੰਟਰਨੈੱਟ ਆਉਣ 'ਤੇ ਜਾਂਚ ਕਰਾਂਗੇ।",
  micPermissionDenied: "Sat-Yukt ਵਰਤਣ ਲਈ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।",
  clearHistory: "ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ",
  noHistoryYet: "ਹਾਲੇ ਤੱਕ ਕੋਈ ਸਵਾਲ ਨਹੀਂ",
  autoDetect: "ਆਪਣੇ ਆਪ ਪਛਾਣੋ",
  forwardWhatsApp: "ਵਟਸਐਪ ਸੁਨੇਹਾ ਅੱਗੇ ਭੇਜੋ",
  getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
  enterPhoneNumber: "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
  phoneNumberHint: "ਤੁਹਾਡੀ ਪਛਾਣ ਦੀ ਪੁਸ਼ਟੀ ਲਈ ਅਸੀਂ ਇੱਕ ਕੋਡ ਭੇਜਾਂਗੇ",
  sendCode: "ਕੋਡ ਭੇਜੋ",
  otpSentTitle: "ਅਸੀਂ ਭੇਜਿਆ ਕੋਡ ਦਰਜ ਕਰੋ",
  verifyCode: "ਪੁਸ਼ਟੀ ਕਰੋ",
  resendCode: "ਕੋਡ ਦੁਬਾਰਾ ਭੇਜੋ",
  otpIncorrect: "ਇਹ ਕੋਡ ਗਲਤ ਹੈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  otpConfigMissing: "OTP ਪੁਸ਼ਟੀਕਰਨ ਅਜੇ ਤਿਆਰ ਨਹੀਂ ਹੈ। ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  otpTestModeHint: "ਟੈਸਟ ਮੋਡ: ਜਾਰੀ ਰੱਖਣ ਲਈ 000000 ਦਰਜ ਕਰੋ।",
  locationPermissionTitle: "ਆਪਣਾ ਟਿਕਾਣਾ ਸਾਂਝਾ ਕਰਨਾ ਹੈ?",
  locationPermissionBody: "ਇਸ ਨਾਲ ਅਸੀਂ ਤੁਹਾਡੇ ਖੇਤਰ ਨਾਲ ਸਬੰਧਤ ਖਬਰਾਂ ਅਤੇ ਯੋਜਨਾਵਾਂ ਦਿਖਾ ਸਕਾਂਗੇ।",
  allowLocation: "ਟਿਕਾਣੇ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ",
  skipForNow: "ਹੁਣ ਲਈ ਛੱਡੋ",
  continueLabel: "ਅੱਗੇ ਵਧੋ",
  typeQuestionPlaceholder: "ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ…",
  send: "ਭੇਜੋ",
  orTypeInstead: "ਜਾਂ ਆਪਣਾ ਸਵਾਲ ਲਿਖੋ",
  profile: "ਪ੍ਰੋਫਾਈਲ",
  contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  faqs: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
  resetOnboarding: "ਓਨਬੋਰਡਿੰਗ ਰੀਸੈੱਟ ਕਰੋ (ਟੈਸਟਿੰਗ ਲਈ)",
  resetOnboardingConfirmTitle: "ਓਨਬੋਰਡਿੰਗ ਰੀਸੈੱਟ ਕਰਨੀ ਹੈ?",
  resetOnboardingConfirmBody: "ਅਗਲੀ ਵਾਰ ਐਪ ਖੋਲ੍ਹਣ 'ਤੇ ਤੁਹਾਨੂੰ ਭਾਸ਼ਾ, ਫ਼ੋਨ ਅਤੇ ਟਿਕਾਣਾ ਦੁਬਾਰਾ ਸੈੱਟ ਕਰਨਾ ਪਵੇਗਾ।",
  cancel: "ਰੱਦ ਕਰੋ",
  phoneNumberLabel: "ਫ਼ੋਨ ਨੰਬਰ",
  notSetYet: "ਅਜੇ ਸੈੱਟ ਨਹੀਂ ਹੈ",
  yourLocation: "ਤੁਹਾਡਾ ਟਿਕਾਣਾ",
  locationNotSet: "ਟਿਕਾਣਾ ਸਾਂਝਾ ਨਹੀਂ ਕੀਤਾ",
  appVersion: "ਐਪ ਵਰਜ਼ਨ",
  contactUsIntro: "ਕੋਈ ਸਵਾਲ, ਸਮੱਸਿਆ ਜਾਂ ਸੁਝਾਅ ਹੈ? ਇੱਥੇ ਸੰਪਰਕ ਕਰੋ:",
  contactPhone: "ਸਾਨੂੰ ਕਾਲ ਕਰੋ",
  contactEmail: "ਸਾਨੂੰ ਈਮੇਲ ਕਰੋ",
  faqQ1: "ਕੀ Sat-Yukt ਵਰਤਣਾ ਮੁਫ਼ਤ ਹੈ?",
  faqA1: "ਹਾਂ, Sat-Yukt ਪੂਰੀ ਤਰ੍ਹਾਂ ਮੁਫ਼ਤ ਹੈ। ਤੁਹਾਡਾ ਸਵਾਲ ਪੁੱਛਣ ਲਈ ਸਿਰਫ਼ ਇੱਕ ਫ਼ੋਨ ਚਾਹੀਦਾ ਹੈ।",
  faqQ2: "ਕੀ ਇਸਨੂੰ ਵਰਤਣ ਲਈ ਇੰਟਰਨੈੱਟ ਚਾਹੀਦਾ ਹੈ?",
  faqA2: "ਨਹੀਂ। ਜੇ ਇੰਟਰਨੈੱਟ ਨਹੀਂ ਹੈ, ਤਾਂ \"SMS ਰਾਹੀਂ ਜਵਾਬ ਪਾਓ\" ਦਬਾਓ ਅਤੇ ਅਸੀਂ ਤੁਹਾਨੂੰ ਜਵਾਬ ਭੇਜਾਂਗੇ।",
  faqQ3: "ਕਿਹੜੀਆਂ ਭਾਸ਼ਾਵਾਂ ਉਪਲਬਧ ਹਨ?",
  faqA3: "Sat-Yukt ਹਿੰਦੀ, ਅੰਗਰੇਜ਼ੀ, ਮਰਾਠੀ, ਤਮਿਲ, ਤੇਲਗੂ, ਬੰਗਾਲੀ, ਗੁਜਰਾਤੀ, ਪੰਜਾਬੀ ਅਤੇ ਕੰਨੜ ਵਿੱਚ ਕੰਮ ਕਰਦਾ ਹੈ।",
  faqQ4: "ਕੀ ਮੇਰਾ ਫ਼ੋਨ ਨੰਬਰ ਨਿੱਜੀ ਰਹਿੰਦਾ ਹੈ?",
  faqA4: "ਹਾਂ। ਤੁਹਾਡਾ ਫ਼ੋਨ ਨੰਬਰ ਸਿਰਫ਼ SMS ਜਵਾਬ ਭੇਜਣ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ ਅਤੇ ਕਿਸੇ ਹੋਰ ਨਾਲ ਸਾਂਝਾ ਨਹੀਂ ਕੀਤਾ ਜਾਂਦਾ।",
  smsTrialUnverified: "ਇਸ ਐਪ ਦੀ SMS ਸੇਵਾ ਅਜੇ ਟੈਸਟ ਮੋਡ ਵਿੱਚ ਹੈ ਅਤੇ ਸਿਰਫ਼ ਕੁਝ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਨੰਬਰਾਂ 'ਤੇ ਹੀ ਭੇਜ ਸਕਦੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਐਪ ਦੇ ਮਾਲਕ ਨੂੰ ਆਪਣਾ ਨੰਬਰ ਜੋੜਨ ਲਈ ਕਹੋ।",
  addPhoneNumberFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ Settings ਵਿੱਚ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਜੋੜੋ।",
  welcomeBack: "ਵਾਪਸ ਆਉਣ 'ਤੇ ਸਵਾਗਤ ਹੈ",
  quickActions: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
  askByVoice: "ਬੋਲ ਕੇ ਪੁੱਛੋ",
  askByTyping: "ਲਿਖ ਕੇ ਪੁੱਛੋ",
  moreOptions: "ਹੋਰ",
  yourDistrict: "ਤੁਹਾਡਾ ਖੇਤਰ",
  latestSchemes: "ਨਵੀਨਤਮ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
  schemesLoadFailed: "ਹੁਣੇ ਯੋਜਨਾਵਾਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  schemesEmpty: "ਹੁਣੇ ਦਿਖਾਉਣ ਲਈ ਕੋਈ ਯੋਜਨਾ ਨਹੀਂ ਹੈ।",
};

const kn: StringTable = {
  tapToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿ",
  listening: "ಕೇಳುತ್ತಿದೆ…",
  tapToStop: "ನಿಲ್ಲಿಸಲು ಒತ್ತಿ",
  analyzing: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…",
  verdictTrue: "ನಿಜ",
  verdictFalse: "ಸುಳ್ಳು",
  verdictMisleading: "ದಾರಿತಪ್ಪಿಸುವ",
  verdictUnclear: "ಅಸ್ಪಷ್ಟ",
  noInternetTitle: "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲವೇ?",
  smsButtonLabel: "SMS ಮೂಲಕ ಉತ್ತರ ಪಡೆಯಿರಿ",
  smsSent: "ಕಳುಹಿಸಲಾಗಿದೆ! ಶೀಘ್ರದಲ್ಲೇ SMS ನಲ್ಲಿ ಉತ್ತರ ಬರುತ್ತದೆ.",
  smsFailed: "SMS ಕಳುಹಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಫೋನ್ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ.",
  yourQuestion: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ",
  listenAgain: "ಮತ್ತೆ ಕೇಳಿ",
  askAnother: "ಇನ್ನೊಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ",
  history: "ಹಳೆಯ ಪ್ರಶ್ನೆಗಳು",
  settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  selectLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  recordingError: "ಆಡಿಯೋ ರೆಕಾರ್ಡ್ ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  networkError: "ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ.",
  genericError: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  welcomeTitle: "Sat-Yukt",
  welcomeSubtitle: "ಸುದ್ದಿ, ಯೋಜನೆಗಳು ಅಥವಾ ಕೃಷಿ ಸಲಹೆ ಬಗ್ಗೆ ಕೇಳಿ",
  queuedOffline: "ಉಳಿಸಲಾಗಿದೆ. ಇಂಟರ್ನೆಟ್ ಬಂದ ನಂತರ ಪರಿಶೀಲಿಸುತ್ತೇವೆ.",
  micPermissionDenied: "Sat-Yukt ಬಳಸಲು ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನೀಡಿ.",
  clearHistory: "ಇತಿಹಾಸ ಅಳಿಸಿ",
  noHistoryYet: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿಲ್ಲ",
  autoDetect: "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪತ್ತೆ ಮಾಡಿ",
  forwardWhatsApp: "ವಾಟ್ಸಾಪ್ ಸಂದೇಶವನ್ನು ಫಾರ್ವರ್ಡ್ ಮಾಡಿ",
  getStarted: "ಪ್ರಾರಂಭಿಸಿ",
  enterPhoneNumber: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  phoneNumberHint: "ನಿಮ್ಮನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು ಒಂದು ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ",
  sendCode: "ಕೋಡ್ ಕಳುಹಿಸಿ",
  otpSentTitle: "ನಾವು ಕಳುಹಿಸಿದ ಕೋಡ್ ಅನ್ನು ನಮೂದಿಸಿ",
  verifyCode: "ಪರಿಶೀಲಿಸಿ",
  resendCode: "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ",
  otpIncorrect: "ಈ ಕೋಡ್ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  otpConfigMissing: "OTP ಪರಿಶೀಲನೆ ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
  otpTestModeHint: "ಟೆಸ್ಟ್ ಮೋಡ್: ಮುಂದುವರಿಸಲು 000000 ನಮೂದಿಸಿ.",
  locationPermissionTitle: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳುವುದೇ?",
  locationPermissionBody: "ಇದು ನಿಮ್ಮ ಪ್ರದೇಶಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಸುದ್ದಿ ಮತ್ತು ಯೋಜನೆಗಳನ್ನು ತೋರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  allowLocation: "ಸ್ಥಳಕ್ಕೆ ಅನುಮತಿ ನೀಡಿ",
  skipForNow: "ಈಗ ಬಿಟ್ಟುಬಿಡಿ",
  continueLabel: "ಮುಂದುವರಿಸಿ",
  typeQuestionPlaceholder: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ…",
  send: "ಕಳುಹಿಸಿ",
  orTypeInstead: "ಅಥವಾ ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ",
  profile: "ಪ್ರೊಫೈಲ್",
  contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  faqs: "ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು",
  resetOnboarding: "ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಅನ್ನು ಮರುಹೊಂದಿಸಿ (ಪರೀಕ್ಷೆಗಾಗಿ)",
  resetOnboardingConfirmTitle: "ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಅನ್ನು ಮರುಹೊಂದಿಸುವುದೇ?",
  resetOnboardingConfirmBody: "ಮುಂದಿನ ಬಾರಿ ಆ್ಯಪ್ ತೆರೆದಾಗ ನೀವು ಭಾಷೆ, ಫೋನ್ ಮತ್ತು ಸ್ಥಳವನ್ನು ಮತ್ತೆ ಹೊಂದಿಸಬೇಕಾಗುತ್ತದೆ.",
  cancel: "ರದ್ದುಮಾಡಿ",
  phoneNumberLabel: "ಫೋನ್ ಸಂಖ್ಯೆ",
  notSetYet: "ಇನ್ನೂ ಹೊಂದಿಸಿಲ್ಲ",
  yourLocation: "ನಿಮ್ಮ ಸ್ಥಳ",
  locationNotSet: "ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಂಡಿಲ್ಲ",
  appVersion: "ಆ್ಯಪ್ ಆವೃತ್ತಿ",
  contactUsIntro: "ಯಾವುದೇ ಪ್ರಶ್ನೆ, ಸಮಸ್ಯೆ ಅಥವಾ ಅಭಿಪ್ರಾಯ ಇದೆಯೇ? ಇಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ:",
  contactPhone: "ನಮಗೆ ಕರೆ ಮಾಡಿ",
  contactEmail: "ನಮಗೆ ಇಮೇಲ್ ಮಾಡಿ",
  faqQ1: "Sat-Yukt ಬಳಸುವುದು ಉಚಿತವೇ?",
  faqA1: "ಹೌದು, Sat-Yukt ಸಂಪೂರ್ಣವಾಗಿ ಉಚಿತ. ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಲು ಒಂದು ಫೋನ್ ಮಾತ್ರ ಬೇಕು.",
  faqQ2: "ಇದನ್ನು ಬಳಸಲು ಇಂಟರ್ನೆಟ್ ಬೇಕೇ?",
  faqA2: "ಇಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದಿದ್ದರೆ \"SMS ಮೂಲಕ ಉತ್ತರ ಪಡೆಯಿರಿ\" ಒತ್ತಿ, ನಾವು ನಿಮಗೆ ಉತ್ತರ ಕಳುಹಿಸುತ್ತೇವೆ.",
  faqQ3: "ಯಾವ ಭಾಷೆಗಳು ಬೆಂಬಲಿತವಾಗಿವೆ?",
  faqA3: "Sat-Yukt ಹಿಂದಿ, ಇಂಗ್ಲಿಷ್, ಮರಾಠಿ, ತಮಿಳು, ತೆಲುಗು, ಬೆಂಗಾಲಿ, ಗುಜರಾತಿ, ಪಂಜಾಬಿ ಮತ್ತು ಕನ್ನಡದಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
  faqQ4: "ನನ್ನ ಫೋನ್ ಸಂಖ್ಯೆ ಖಾಸಗಿಯಾಗಿ ಇರುತ್ತದೆಯೇ?",
  faqA4: "ಹೌದು. ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು SMS ಉತ್ತರಗಳನ್ನು ಕಳುಹಿಸಲು ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ಇತರರೊಂದಿಗೆ ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
  smsTrialUnverified: "ಈ ಆ್ಯಪ್‌ನ SMS ಸೇವೆ ಇನ್ನೂ ಪರೀಕ್ಷಾ ಮೋಡ್‌ನಲ್ಲಿದೆ ಮತ್ತು ಕೆಲವು ಅನುಮೋದಿತ ಸಂಖ್ಯೆಗಳಿಗೆ ಮಾತ್ರ ಕಳುಹಿಸಬಹುದು. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಲು ಆ್ಯಪ್ ಮಾಲೀಕರನ್ನು ಕೇಳಿ.",
  addPhoneNumberFirst: "ದಯವಿಟ್ಟು ಮೊದಲು Settings ನಲ್ಲಿ ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ.",
  welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
  quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
  askByVoice: "ಮಾತನಾಡಿ ಕೇಳಿ",
  askByTyping: "ಟೈಪ್ ಮಾಡಿ ಕೇಳಿ",
  moreOptions: "ಇನ್ನಷ್ಟು",
  yourDistrict: "ನಿಮ್ಮ ಪ್ರದೇಶ",
  latestSchemes: "ಇತ್ತೀಚಿನ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
  schemesLoadFailed: "ಈಗ ಯೋಜನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  schemesEmpty: "ಈಗ ತೋರಿಸಲು ಯಾವುದೇ ಯೋಜನೆಗಳಿಲ್ಲ.",
};

const TABLES: Record<SupportedLanguageCode, StringTable> = {
  en,
  hi,
  mr,
  ta,
  te,
  bn,
  gu,
  pa,
  kn,
};

export function t(lang: SupportedLanguageCode, key: StringKey): string {
  return TABLES[lang]?.[key] ?? TABLES.en[key];
}
